### ISSUE TITLE
HTTP ECONNRESET when scraping schede

### ISSUE THREAD

**Issue by Guberlo** [Guberlo/opis-manager-scraper-2020#1]
I found out this problem when scraping schede, I'm not sure if it shows up because of the high number of request sent.

<details>
    <summary> Error </summary>

    `     node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

            <ref *1> Error: Client network socket disconnected before secure TLS connection was established
                at connResetException (node:internal/errors:631:14)
                at TLSSocket.onConnectEnd (node:_tls_wrap:1545:19)
                at TLSSocket.emit (node:events:388:22)
                at endReadableNT (node:internal/streams/readable:1294:12)
                at processTicksAndRejections (node:internal/process/task_queues:80:21) {
            code: 'ECONNRESET',
            path: null,
            host: 'pqa.unict.it',
            port: 443,
            localAddress: undefined,
            config: {
                url: 'https://pqa.unict.it/opis/_val_insegn.php?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98',
                method: 'get',
                headers: {
                Accept: 'application/json, text/plain, */*',
                'User-Agent': 'axios/0.21.0'
                },
                transformRequest: [ [Function: transformRequest] ],
                transformResponse: [ [Function: transformResponse] ],
                timeout: 0,
                adapter: [Function: httpAdapter],
                xsrfCookieName: 'XSRF-TOKEN',
                xsrfHeaderName: 'X-XSRF-TOKEN',
                maxContentLength: -1,
                maxBodyLength: -1,
                validateStatus: [Function: validateStatus],
                data: undefined
            },
            request: <ref *4> Writable {
                _writableState: WritableState {
                objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: true,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
                writecb: null,
                writelen: 0,
                afterWriteTickInfo: null,
                buffered: [],
                bufferedIndex: 0,
                allBuffers: true,
                allNoop: true,
                pendingcb: 0,
                constructed: true,
                prefinished: false,
                errorEmitted: false,
                emitClose: true,
                autoDestroy: true,
                errored: null,
                closed: false,
                closeEmitted: false,
                [Symbol(kOnFinished)]: []
                },
                _events: [Object: null prototype] {
                response: [Function: handleResponse],
                error: [Function: handleRequestError]
                },
                _eventsCount: 2,
                _maxListeners: undefined,
                _options: {
                maxRedirects: 21,
                maxBodyLength: 10485760,
                protocol: 'https:',
                path: '/opis/_val_insegn.php?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98',
                method: 'GET',
                headers: {
                    Accept: 'application/json, text/plain, */*',
                    'User-Agent': 'axios/0.21.0'
                },
                agent: undefined,
                agents: { http: undefined, https: undefined },
                auth: undefined,
                hostname: 'pqa.unict.it',
                port: null,
                nativeProtocols: {
                    'http:': {
                    _connectionListener: [Function: connectionListener],
                    METHODS: [
                        'ACL',        'BIND',        'CHECKOUT',
                        'CONNECT',    'COPY',        'DELETE',
                        'GET',        'HEAD',        'LINK',
                        'LOCK',       'M-SEARCH',    'MERGE',
                        'MKACTIVITY', 'MKCALENDAR',  'MKCOL',
                        'MOVE',       'NOTIFY',      'OPTIONS',
                        'PATCH',      'POST',        'PRI',
                        'PROPFIND',   'PROPPATCH',   'PURGE',
                        'PUT',        'REBIND',      'REPORT',
                        'SEARCH',     'SOURCE',      'SUBSCRIBE',
                        'TRACE',      'UNBIND',      'UNLINK',
                        'UNLOCK',     'UNSUBSCRIBE'
                    ],
                    STATUS_CODES: {
                        '100': 'Continue',
                        '101': 'Switching Protocols',
                        '102': 'Processing',
                        '103': 'Early Hints',
                        '200': 'OK',
                        '201': 'Created',
                        '202': 'Accepted',
                        '203': 'Non-Authoritative Information',
                        '204': 'No Content',
                        '205': 'Reset Content',
                        '206': 'Partial Content',
                        '207': 'Multi-Status',
                        '208': 'Already Reported',
                        '226': 'IM Used',
                        '300': 'Multiple Choices',
                        '301': 'Moved Permanently',
                        '302': 'Found',
                        '303': 'See Other',
                        '304': 'Not Modified',
                        '305': 'Use Proxy',
                        '307': 'Temporary Redirect',
                        '308': 'Permanent Redirect',
                        '400': 'Bad Request',
                        '401': 'Unauthorized',
                        '402': 'Payment Required',
                        '403': 'Forbidden',
                        '404': 'Not Found',
                        '405': 'Method Not Allowed',
                        '406': 'Not Acceptable',
                        '407': 'Proxy Authentication Required',
                        '408': 'Request Timeout',
                        '409': 'Conflict',
                        '410': 'Gone',
                        '411': 'Length Required',
                        '412': 'Precondition Failed',
                        '413': 'Payload Too Large',
                        '414': 'URI Too Long',
                        '415': 'Unsupported Media Type',
                        '416': 'Range Not Satisfiable',
                        '417': 'Expectation Failed',
                        '418': "I'm a Teapot",
                        '421': 'Misdirected Request',
                        '422': 'Unprocessable Entity',
                        '423': 'Locked',
                        '424': 'Failed Dependency',
                        '425': 'Too Early',
                        '426': 'Upgrade Required',
                        '428': 'Precondition Required',
                        '429': 'Too Many Requests',
                        '431': 'Request Header Fields Too Large',
                        '451': 'Unavailable For Legal Reasons',
                        '500': 'Internal Server Error',
                        '501': 'Not Implemented',
                        '502': 'Bad Gateway',
                        '503': 'Service Unavailable',
                        '504': 'Gateway Timeout',
                        '505': 'HTTP Version Not Supported',
                        '506': 'Variant Also Negotiates',
                        '507': 'Insufficient Storage',
                        '508': 'Loop Detected',
                        '509': 'Bandwidth Limit Exceeded',
                        '510': 'Not Extended',
                        '511': 'Network Authentication Required'
                    },
                    Agent: [Function: Agent] { defaultMaxSockets: Infinity },
                    ClientRequest: [Function: ClientRequest],
                    IncomingMessage: [Function: IncomingMessage],
                    OutgoingMessage: [Function: OutgoingMessage],
                    Server: [Function: Server],
                    ServerResponse: [Function: ServerResponse],
                    createServer: [Function: createServer],
                    validateHeaderName: [Function: hidden],
                    validateHeaderValue: [Function: hidden],
                    get: [Function: get],
                    request: [Function: request],
                    maxHeaderSize: [Getter],
                    globalAgent: [Getter/Setter]
                    },
                    'https:': {
                    Agent: [Function: Agent],
                    globalAgent: Agent {
                        _events: [Object: null prototype],
                        _eventsCount: 2,
                        _maxListeners: undefined,
                        defaultPort: 443,
                        protocol: 'https:',
                        options: [Object],
                        requests: {},
                        sockets: [Object],
                        freeSockets: {},
                        keepAliveMsecs: 1000,
                        keepAlive: false,
                        maxSockets: Infinity,
                        maxFreeSockets: 256,
                        scheduling: 'fifo',
                        maxTotalSockets: Infinity,
                        totalSocketCount: 564,
                        maxCachedSessions: 100,
                        _sessionCache: [Object],
                        [Symbol(kCapture)]: false
                    },
                    Server: [Function: Server],
                    createServer: [Function: createServer],
                    get: [Function: get],
                    request: [Function: request]
                    }
                },
                pathname: '/opis/_val_insegn.php',
                search: '?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98'
                },
                _ended: true,
                _ending: true,
                _redirectCount: 0,
                _redirects: [],
                _requestBodyLength: 0,
                _requestBodyBuffers: [],
                _onNativeResponse: [Function (anonymous)],
                _currentRequest: <ref *2> ClientRequest {
                _events: [Object: null prototype] {
                    response: [Function: bound onceWrapper] {
                    listener: [Function (anonymous)]
                    },
                    socket: [Function (anonymous)],
                    abort: [Function (anonymous)],
                    aborted: [Function (anonymous)],
                    connect: [Function (anonymous)],
                    error: [Function (anonymous)],
                    timeout: [Function (anonymous)]
                },
                _eventsCount: 7,
                _maxListeners: undefined,
                outputData: [],
                outputSize: 0,
                writable: true,
                destroyed: false,
                _last: true,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                _defaultKeepAlive: true,
                useChunkedEncodingByDefault: false,
                sendDate: false,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: 0,
                _hasBody: true,
                _trailer: '',
                finished: true,
                _headerSent: true,
                _closed: false,
                socket: <ref *3> TLSSocket {
                    _tlsOptions: {
                    allowHalfOpen: undefined,
                    pipe: false,
                    secureContext: SecureContext { context: SecureContext {}, singleUse: true },
                    isServer: false,
                    requestCert: true,
                    rejectUnauthorized: true,
                    session: Buffer(2240) [Uint8Array] [
                        48, 130,   8, 188,   2,   1,   1,   2,   2,   3,   3,   4,
                        2, 192,  48,   4,  32,  93,  39, 126,  70, 167,   0, 244,
                        105,   1, 248, 204, 219, 147,   2, 141, 210, 247,  78, 170,
                        87, 193,  14, 117, 241, 205, 203, 192, 212, 142, 175,  93,
                        223,   4,  48, 235, 185, 106, 181, 191, 137,  41,  86,  40,
                        242, 249,  43, 130,  63,  26, 121,  94, 219,  54, 102,  32,
                        17, 104, 109,  13, 201,  99, 130,  55, 211, 204, 128, 201,
                        247,   9,  15,  67,  27, 116, 165, 197, 200, 220,  16, 199,
                        176,  51, 124, 161,
                        ... 2140 more items
                    ],
                    ALPNProtocols: undefined,
                    requestOCSP: undefined,
                    enableTrace: undefined,
                    pskCallback: undefined,
                    highWaterMark: undefined,
                    onread: undefined
                    },
                    _secureEstablished: false,
                    _securePending: false,
                    _newSessionPending: false,
                    _controlReleased: true,
                    secureConnecting: true,
                    _SNICallback: null,
                    servername: null,
                    alpnProtocol: null,
                    authorized: false,
                    authorizationError: null,
                    encrypted: true,
                    _events: [Object: null prototype] {
                    close: [
                        [Function: onSocketCloseDestroySSL],
                        [Function],
                        [Function: onClose],
                        [Function: socketCloseListener]
                    ],
                    end: [ [Function: onConnectEnd], [Function: onReadableStreamEnd] ],
                    newListener: [Function: keylogNewListener],
                    secure: [Function: onConnectSecure],
                    session: [Function (anonymous)],
                    free: [Function: onFree],
                    timeout: [Function: onTimeout],
                    agentRemove: [Function: onRemove],
                    error: [Function: socketErrorListener],
                    drain: [Function: ondrain]
                    },
                    _eventsCount: 10,
                    connecting: false,
                    _hadError: true,
                    _parent: null,
                    _host: 'pqa.unict.it',
                    _readableState: ReadableState {
                    objectMode: false,
                    highWaterMark: 16384,
                    buffer: BufferList { head: null, tail: null, length: 0 },
                    length: 0,
                    pipes: [],
                    flowing: true,
                    ended: true,
                    endEmitted: true,
                    reading: false,
                    constructed: true,
                    sync: false,
                    needReadable: false,
                    emittedReadable: false,
                    readableListening: false,
                    resumeScheduled: false,
                    errorEmitted: true,
                    emitClose: false,
                    autoDestroy: true,
                    destroyed: true,
                    errored: [Circular *1],
                    closed: true,
                    closeEmitted: true,
                    defaultEncoding: 'utf8',
                    awaitDrainWriters: null,
                    multiAwaitDrain: false,
                    readingMore: false,
                    decoder: null,
                    encoding: null,
                    [Symbol(kPaused)]: false
                    },
                    _maxListeners: undefined,
                    _writableState: WritableState {
                    objectMode: false,
                    highWaterMark: 16384,
                    finalCalled: false,
                    needDrain: false,
                    ending: false,
                    ended: false,
                    finished: false,
                    destroyed: true,
                    decodeStrings: false,
                    defaultEncoding: 'utf8',
                    length: 226,
                    writing: true,
                    corked: 0,
                    sync: false,
                    bufferProcessing: false,
                    onwrite: [Function: bound onwrite],
                    writecb: [Function: bound onFinish],
                    writelen: 226,
                    afterWriteTickInfo: null,
                    buffered: [],
                    bufferedIndex: 0,
                    allBuffers: true,
                    allNoop: true,
                    pendingcb: 1,
                    constructed: true,
                    prefinished: false,
                    errorEmitted: true,
                    emitClose: false,
                    autoDestroy: true,
                    errored: [Circular *1],
                    closed: true,
                    closeEmitted: true,
                    [Symbol(kOnFinished)]: []
                    },
                    allowHalfOpen: false,
                    _sockname: null,
                    _pendingData: null,
                    _pendingEncoding: '',
                    server: undefined,
                    _server: null,
                    ssl: null,
                    _requestCert: true,
                    _rejectUnauthorized: true,
                    parser: null,
                    _httpMessage: [Circular *2],
                    write: [Function: writeAfterFIN],
                    [Symbol(res)]: TLSWrap {
                    _parent: TCP {
                        reading: [Getter/Setter],
                        onconnection: null,
                        [Symbol(owner_symbol)]: [Circular *3],
                        [Symbol(handle_onclose)]: [Function: done]
                    },
                    _parentWrap: undefined,
                    _secureContext: SecureContext { context: SecureContext {}, singleUse: true },
                    reading: true,
                    onkeylog: [Function: onkeylog],
                    onhandshakestart: [Function: noop],
                    onhandshakedone: [Function (anonymous)],
                    onocspresponse: [Function: onocspresponse],
                    onnewsession: [Function: onnewsessionclient],
                    onerror: [Function: onerror],
                    [Symbol(owner_symbol)]: [Circular *3]
                    },
                    [Symbol(verified)]: false,
                    [Symbol(pendingSession)]: null,
                    [Symbol(async_id_symbol)]: 10695,
                    [Symbol(kHandle)]: null,
                    [Symbol(kSetNoDelay)]: false,
                    [Symbol(lastWriteQueueSize)]: 226,
                    [Symbol(timeout)]: null,
                    [Symbol(kBuffer)]: null,
                    [Symbol(kBufferCb)]: null,
                    [Symbol(kBufferGen)]: null,
                    [Symbol(kCapture)]: false,
                    [Symbol(kBytesRead)]: 0,
                    [Symbol(kBytesWritten)]: 226,
                    [Symbol(connect-options)]: {
                    rejectUnauthorized: true,
                    ciphers: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
                    checkServerIdentity: [Function: checkServerIdentity],
                    minDHSize: 1024,
                    session: Buffer(2240) [Uint8Array] [
                        48, 130,   8, 188,   2,   1,   1,   2,   2,   3,   3,   4,
                        2, 192,  48,   4,  32,  93,  39, 126,  70, 167,   0, 244,
                        105,   1, 248, 204, 219, 147,   2, 141, 210, 247,  78, 170,
                        87, 193,  14, 117, 241, 205, 203, 192, 212, 142, 175,  93,
                        223,   4,  48, 235, 185, 106, 181, 191, 137,  41,  86,  40,
                        242, 249,  43, 130,  63,  26, 121,  94, 219,  54, 102,  32,
                        17, 104, 109,  13, 201,  99, 130,  55, 211, 204, 128, 201,
                        247,   9,  15,  67,  27, 116, 165, 197, 200, 220,  16, 199,
                        176,  51, 124, 161,
                        ... 2140 more items
                    ],
                    maxRedirects: 21,
                    maxBodyLength: 10485760,
                    protocol: 'https:',
                    path: null,
                    method: 'GET',
                    headers: {
                        Accept: 'application/json, text/plain, */*',
                        'User-Agent': 'axios/0.21.0'
                    },
                    agent: undefined,
                    agents: { http: undefined, https: undefined },
                    auth: undefined,
                    hostname: 'pqa.unict.it',
                    port: 443,
                    nativeProtocols: { 'http:': [Object], 'https:': [Object] },
                    pathname: '/opis/_val_insegn.php',
                    search: '?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98',
                    _defaultAgent: Agent {
                        _events: [Object: null prototype],
                        _eventsCount: 2,
                        _maxListeners: undefined,
                        defaultPort: 443,
                        protocol: 'https:',
                        options: [Object],
                        requests: {},
                        sockets: [Object],
                        freeSockets: {},
                        keepAliveMsecs: 1000,
                        keepAlive: false,
                        maxSockets: Infinity,
                        maxFreeSockets: 256,
                        scheduling: 'fifo',
                        maxTotalSockets: Infinity,
                        totalSocketCount: 564,
                        maxCachedSessions: 100,
                        _sessionCache: [Object],
                        [Symbol(kCapture)]: false
                    },
                    host: 'pqa.unict.it',
                    servername: 'pqa.unict.it',
                    _agentKey: 'pqa.unict.it:443::::::::::::::::::',
                    encoding: null,
                    singleUse: true
                    }
                },
                _header: 'GET /opis/_val_insegn.php?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98 HTTP/1.1\r\n' +
                    'Accept: application/json, text/plain, */*\r\n' +
                    'User-Agent: axios/0.21.0\r\n' +
                    'Host: pqa.unict.it\r\n' +
                    'Connection: close\r\n' +
                    '\r\n',
                _keepAliveTimeout: 0,
                _onPendingData: [Function: noopPendingOutput],
                agent: Agent {
                    _events: [Object: null prototype] {
                    free: [Function (anonymous)],
                    newListener: [Function: maybeEnableKeylog]
                    },
                    _eventsCount: 2,
                    _maxListeners: undefined,
                    defaultPort: 443,
                    protocol: 'https:',
                    options: { path: null },
                    requests: {},
                    sockets: {
                    'pqa.unict.it:443::::::::::::::::::': [
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket], [TLSSocket],
                        ... 464 more items
                    ]
                    },
                    freeSockets: {},
                    keepAliveMsecs: 1000,
                    keepAlive: false,
                    maxSockets: Infinity,
                    maxFreeSockets: 256,
                    scheduling: 'fifo',
                    maxTotalSockets: Infinity,
                    totalSocketCount: 564,
                    maxCachedSessions: 100,
                    _sessionCache: {
                    map: {
                        'pqa.unict.it:443::::::::::::::::::': [Buffer [Uint8Array]]
                    },
                    list: [ 'pqa.unict.it:443::::::::::::::::::' ]
                    },
                    [Symbol(kCapture)]: false
                },
                socketPath: undefined,
                method: 'GET',
                maxHeaderSize: undefined,
                insecureHTTPParser: undefined,
                path: '/opis/_val_insegn.php?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98',
                _ended: false,
                res: null,
                aborted: false,
                timeoutCb: null,
                upgradeOrConnect: false,
                parser: null,
                maxHeadersCount: null,
                reusedSocket: false,
                host: 'pqa.unict.it',
                protocol: 'https:',
                _redirectable: [Circular *4],
                [Symbol(kCapture)]: false,
                [Symbol(kNeedDrain)]: false,
                [Symbol(corked)]: 0,
                [Symbol(kOutHeaders)]: [Object: null prototype] {
                    accept: [ 'Accept', 'application/json, text/plain, */*' ],
                    'user-agent': [ 'User-Agent', 'axios/0.21.0' ],
                    host: [ 'Host', 'pqa.unict.it' ]
                }
                },
                _currentUrl: 'https://pqa.unict.it/opis/_val_insegn.php?aa=2019&ins=1010727&mod=1010728&canale=4&s1=29&s3=0&id=328&classe=LM-41&cds=L98',
                [Symbol(kCapture)]: false
            },
            response: undefined,
            isAxiosError: true,
            toJSON: [Function: toJSON],
            status: 500
} `
</details>

**Comment by ErliSoares** [comment]
Any news? I have the same problem.

**Comment by Guberlo** [comment]
The error shows up after scraping all departments, cds, teachings (between 100-200 scraped schede)
