### ISSUE TITLE
Testing and reports

### ISSUE THREAD

**Issue by Helias** [Guberlo/opis-manager-scraper-2020#5]
- [x] the year should be 2019/2020, not 2020/2021
- [x] Remove "Dipartimento di" and not sure if keep the acronym inside the parenthesis like (Di3A)
![image](https://user-images.githubusercontent.com/519778/111903462-be4b1b80-8a42-11eb-8da1-68da2390bf0d.png)

- [x] unict_id should be a number, example Archeologia unict_id 375 not Y53.
EDIT: I think this is an issue of the system that now is incoherent with the previous data, so we should change the back-end and accept even strings for this field
We need to create a map of the id_cds (unict_id) to convert these IDs into the same IDs of the previous years
- [x] (same for the IDs of dipartimento)

for these 2 I would suggest a key-value mapping of these IDs client side or back-end side

**Comment by Guberlo** [comment]
The first two problems have been solved.

The main problem now is the mapping: 
I thought to just join the two differents ids using the name, unfortunately in some cases this is not possible;
Indeed there are some new CDS which are not present in the old data, hence making it not possible to map with anything.

I'm going to give a quick look at the back-end side to see if it is possible to maintain this new ID structure.

**Comment by Helias** [comment]
Ok, if the CDS are new we can use the new IDs

**Comment by Guberlo** [comment]
Finally everything should work properly! ( at least until the next update . . . )
